<?php
/**
 * Created by IntelliJ IDEA.
 * User: 七友
 * Date: 2019/5/28
 * Time: 8:59
 */

namespace app\user\model;


use think\Model;

class Host extends Model
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}